# Generated by Django 6.0.2 on 2026-03-01 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_turns', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(default='Learner', max_length=100)),
                ('ld_confirmed', models.JSONField(default=list)),
                ('ld_suspected', models.JSONField(default=list)),
                ('ld_severity', models.JSONField(default=dict)),
                ('wm_span', models.FloatField(default=5.0)),
                ('attention_min', models.FloatField(default=15.0)),
                ('initiation_latency', models.FloatField(default=20.0)),
                ('frustration_thresh', models.FloatField(default=0.55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('active_agent', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wm_load', models.FloatField(null=True)),
                ('motivation', models.FloatField(null=True)),
                ('affect', models.FloatField(null=True)),
                ('fatigue', models.FloatField(null=True)),
                ('risk_score', models.FloatField(null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tutor.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tutor.learnerprofile'),
        ),
    ]
