# Generated by Django 6.0.3 on 2026-03-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_ieltssection_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltsquestion',
            name='group_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
