# Generated by Django 6.0.3 on 2026-03-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_add_group_instruction_to_ieltsequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingStrategyExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_variant', models.CharField(max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='tutor.readingattempt')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_experiments', to='tutor.learnerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_variant', models.CharField(max_length=50)),
                ('ld_profile_type', models.CharField(max_length=50)),
                ('total_attempts', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('avg_hints_used', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-avg_score'],
                'unique_together': {('strategy_variant', 'ld_profile_type')},
            },
        ),
    ]
