# Generated by Django 6.0.3 on 2026-03-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0007_add_strategy_optimizer_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakingPractice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topic", models.CharField(blank=True, default="", max_length=200)),
                ("scenario", models.CharField(blank=True, default="", max_length=200)),
                ("english_level", models.CharField(blank=True, default="A2-B1", max_length=50)),
                ("minutes_budget", models.PositiveSmallIntegerField(default=8)),
                ("pack_markdown", models.TextField(blank=True, default="")),
                ("history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_practices",
                        to="tutor.learnerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]

