# agents/strategy_optimizer.py
# ─────────────────────────────────────────────────────────────────
# EduwHealth 2.0  –  Anonymous Agent Strategy Optimizer
#
# Responsibilities:
#   1. Aggregate anonymised strategy performance data across learner
#      cohorts (no PII — only LD profile type + variant performance).
#   2. Use an LLM to generate improved strategy variants when current
#      variants underperform.
#   3. A/B-test new variants automatically and log all changes for
#      human review before promotion.
# ─────────────────────────────────────────────────────────────────
from __future__ import annotations

import logging
import random
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ── Mode → variant seed mapping ──────────────────────────────────
# Each assistant mode maps to a named variant family.
# New variants generated by the optimizer follow the same naming
# convention: "<mode>_v<n>".
MODE_VARIANT_MAP: Dict[str, str] = {
    "auto":  "auto_v1",
    "focus": "focus_v1",
    "calm":  "calm_v1",
    "speed": "speed_v1",
}

# Minimum attempts required before a variant can be considered for
# optimisation (avoids noise from very small samples).
MIN_ATTEMPTS_FOR_OPTIMISATION = 5

# Performance threshold below which a variant is deemed under-
# performing and a new variant is generated.
UNDERPERFORM_THRESHOLD = 0.5  # avg_score < 50 %


class StrategyOptimizerAgent:
    """
    Analyses historical strategy performance and suggests optimisations.

    Works exclusively with anonymised aggregate data to improve strategies
    for future learners — no individual PII is ever accessed.
    """

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def optimize_strategy(
        self,
        current_strategy: Dict[str, Any],
        ld_profile: Dict[str, Any],
        performance_data: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Generate an optimised strategy variant using LLM reasoning.

        Args:
            current_strategy: Dict with at least ``variant`` and ``content``
                               (Markdown) keys describing the current strategy.
            ld_profile:        Dict with ``confirmed`` and ``suspected`` LD
                               type lists.
            performance_data:  Dict with ``avg_score``, ``avg_hints_used``,
                               and ``total_attempts`` keys.

        Returns:
            {
                'optimized_strategy': str,   # New Markdown strategy text
                'confidence': float,          # 0–1 confidence score
                'changes': [str, ...],        # Human-readable change list
            }
        """
        avg_score    = performance_data.get('avg_score', 0.0)
        hints_used   = performance_data.get('avg_hints_used', 0.0)
        total        = performance_data.get('total_attempts', 0)
        all_ld       = set(
            ld_profile.get('confirmed', []) + ld_profile.get('suspected', [])
        )
        variant      = current_strategy.get('variant', 'auto_v1')
        current_text = current_strategy.get('content', '')

        changes: List[str] = []
        confidence = 0.5

        if total < MIN_ATTEMPTS_FOR_OPTIMISATION:
            return {
                'optimized_strategy': current_text,
                'confidence': confidence,
                'changes': ['Insufficient data — strategy unchanged.'],
            }

        optimized = self._llm_optimize(
            current_text=current_text,
            ld_types=list(all_ld),
            avg_score=avg_score,
            avg_hints=hints_used,
        )

        if avg_score < UNDERPERFORM_THRESHOLD:
            changes.append(
                f"Variant {variant!r} underperformed (avg score "
                f"{avg_score:.0%}). Generated improved variant."
            )
            confidence = 0.75
        else:
            changes.append(
                f"Minor improvements applied (avg score {avg_score:.0%})."
            )
            confidence = 0.6

        if hints_used > 3:
            changes.append(
                "Added explicit paragraph-scanning instruction to reduce hint dependency."
            )

        return {
            'optimized_strategy': optimized,
            'confidence': confidence,
            'changes': changes,
        }

    def analyze_cohort_performance(self, ld_type: str) -> Dict[str, Any]:
        """Return best-performing strategy variants for a given LD profile type.

        Queries the ``StrategyPerformance`` database model and returns a
        ranked summary.

        Args:
            ld_type: A single LD type string, e.g. ``"adhd"``.

        Returns:
            {
                'ld_type': str,
                'best_variant': str | None,
                'variants': [{'variant': str, 'avg_score': float, 'total_attempts': int}, ...],
                'recommendation': str,
            }
        """
        try:
            from tutor.models import StrategyPerformance
            records = (
                StrategyPerformance.objects.filter(ld_profile_type=ld_type)
                .order_by('-avg_score')
            )

            variants = [
                {
                    'variant': r.strategy_variant,
                    'avg_score': r.avg_score,
                    'avg_hints_used': r.avg_hints_used,
                    'total_attempts': r.total_attempts,
                }
                for r in records
            ]

            best = variants[0] if variants else None
            recommendation = (
                f"Best variant for {ld_type!r} learners: "
                f"{best['variant']} (avg score {best['avg_score']:.0%})"
                if best else
                f"No performance data yet for {ld_type!r} learners."
            )

            return {
                'ld_type': ld_type,
                'best_variant': best['variant'] if best else None,
                'variants': variants,
                'recommendation': recommendation,
            }
        except Exception as exc:
            logger.warning("analyze_cohort_performance failed: %s", exc)
            return {
                'ld_type': ld_type,
                'best_variant': None,
                'variants': [],
                'recommendation': 'Performance data unavailable.',
            }

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _llm_optimize(
        self,
        current_text: str,
        ld_types: List[str],
        avg_score: float,
        avg_hints: float,
    ) -> str:
        """Call the LLM to generate an improved strategy.

        Falls back to a rule-based improvement if the LLM is unavailable.
        """
        try:
            from core.llm_client import LLMClient

            ld_str = ', '.join(ld_types) if ld_types else 'general'
            prompt = (
                f"You are an expert learning strategist for learners with learning "
                f"differences ({ld_str}).\n\n"
                f"The following reading strategy currently achieves an average score of "
                f"{avg_score:.0%} and requires an average of {avg_hints:.1f} hints per attempt:\n\n"
                f"---\n{current_text}\n---\n\n"
                f"Generate an improved version of this strategy. Focus on:\n"
                f"1. Reducing hint dependency (current avg: {avg_hints:.1f})\n"
                f"2. Improving comprehension accuracy\n"
                f"3. Adapting specifically for {ld_str} learners\n\n"
                f"Return only the new Markdown-formatted strategy. Keep it concise."
            )
            llm = LLMClient()
            return llm.chat(
                system="You are a learning strategy optimiser. Return only the improved strategy, in Markdown.",
                user=prompt,
                temperature=0.5,
                max_tokens=400,
            )
        except Exception as exc:
            logger.warning("LLM optimisation failed, using rule-based fallback: %s", exc)
            return self._rule_based_optimize(current_text, ld_types, avg_score, avg_hints)

    def _rule_based_optimize(
        self,
        current_text: str,
        ld_types: List[str],
        avg_score: float,
        avg_hints: float,
    ) -> str:
        """Rule-based strategy improvement when LLM is unavailable."""
        lines = [current_text.rstrip()]
        if avg_score < UNDERPERFORM_THRESHOLD:
            lines.append(
                "\n\n---\n**📈 Optimizer Note (auto-generated)**\n\n"
                "Based on cohort performance data, add these steps:\n"
                "1. Re-read the paragraph heading before answering.\n"
                "2. Circle key nouns and verbs in each question first.\n"
                "3. Use the Scan-Locate-Verify method for detail questions."
            )
        if avg_hints > 3 and 'adhd' in ld_types:
            lines.append(
                "\n⚡ **ADHD optimizer:** Write a one-sentence summary of each "
                "paragraph before answering — this reduces the need for hints."
            )
        return '\n'.join(lines)


# ── Periodic background optimisation job ─────────────────────────

def run_strategy_optimization() -> Dict[str, Any]:
    """Periodic job (designed to be run daily) that:

    1. Aggregates strategy performance by LD type.
    2. Identifies under-performing variants.
    3. Uses the LLM to generate improved variants.
    4. Logs all changes for human review (does *not* auto-deploy).

    Returns a summary dict suitable for logging or an admin dashboard.
    """
    from django.db.models import Avg, Count

    log: List[str] = []
    optimised: List[Dict[str, Any]] = []

    try:
        from tutor.models import StrategyPerformance, ReadingStrategyExperiment

        # ── Step 1: aggregate completed experiments ────────────────
        completed_qs = ReadingStrategyExperiment.objects.filter(
            completed=True, score__isnull=False
        )

        # Group by (strategy_variant, ld_profile_type via learner)
        from django.db.models import F
        agg = (
            completed_qs
            .values('strategy_variant')
            .annotate(
                total=Count('id'),
                avg_sc=Avg('score'),
                avg_h=Avg('attempt__hints_used'),
            )
        )

        for row in agg:
            variant = row['strategy_variant']
            total   = row['total']
            avg_sc  = row['avg_sc'] or 0.0
            avg_h   = row['avg_h'] or 0.0

            # Infer LD type from variant name (e.g. "focus_v1" → "adhd")
            ld_type = _variant_to_ld_type(variant)

            StrategyPerformance.objects.update_or_create(
                strategy_variant=variant,
                ld_profile_type=ld_type,
                defaults={
                    'total_attempts': total,
                    'avg_score': avg_sc,
                    'avg_hints_used': avg_h,
                },
            )
            log.append(
                f"Updated StrategyPerformance: {variant}/{ld_type} "
                f"— {total} attempts, avg score {avg_sc:.0%}"
            )

        # ── Step 2: identify under-performers ─────────────────────
        under = StrategyPerformance.objects.filter(
            avg_score__lt=UNDERPERFORM_THRESHOLD,
            total_attempts__gte=MIN_ATTEMPTS_FOR_OPTIMISATION,
        )

        agent = StrategyOptimizerAgent()

        for perf in under:
            result = agent.optimize_strategy(
                current_strategy={'variant': perf.strategy_variant, 'content': ''},
                ld_profile={'confirmed': [perf.ld_profile_type], 'suspected': []},
                performance_data={
                    'avg_score': perf.avg_score,
                    'avg_hints_used': perf.avg_hints_used,
                    'total_attempts': perf.total_attempts,
                },
            )
            optimised.append({
                'variant': perf.strategy_variant,
                'ld_type': perf.ld_profile_type,
                'result': result,
            })
            log.append(
                f"Optimised {perf.strategy_variant!r} "
                f"(confidence {result['confidence']:.0%}): "
                + '; '.join(result['changes'])
            )

    except Exception as exc:
        logger.error("run_strategy_optimization failed: %s", exc)
        log.append(f"ERROR: {exc}")

    summary = {
        'log': log,
        'optimised_variants': optimised,
        'status': 'ok' if optimised is not None else 'error',
    }
    logger.info("Strategy optimisation complete: %d variants updated.", len(optimised))
    return summary


def assign_strategy_variant(ld_profile: dict, mode: str = 'auto') -> str:
    """Assign a strategy variant for A/B testing.

    Looks up the best-performing variant for this LD profile.  If no data
    exists yet, randomly picks between the current best and a challenger
    so that new variants accrue data.

    Args:
        ld_profile: Learner LD profile dict.
        mode:       Requested assistant mode ('auto', 'focus', 'calm', 'speed').

    Returns:
        Variant name string (e.g. ``"focus_v1"``).
    """
    # Mode overrides automatic assignment
    if mode != 'auto':
        return MODE_VARIANT_MAP.get(mode, 'auto_v1')

    all_ld = set(ld_profile.get('confirmed', []) + ld_profile.get('suspected', []))
    ld_type = _ld_set_to_primary(all_ld)

    try:
        from tutor.models import StrategyPerformance
        best = (
            StrategyPerformance.objects.filter(ld_profile_type=ld_type)
            .order_by('-avg_score')
            .first()
        )
        if best:
            # 80 % chance of best variant, 20 % challenger (next best or new v2)
            if random.random() < 0.8:
                return best.strategy_variant
            # Try next best; fall back to generating a new variant label
            second = (
                StrategyPerformance.objects.filter(ld_profile_type=ld_type)
                .exclude(strategy_variant=best.strategy_variant)
                .order_by('-avg_score')
                .first()
            )
            if second:
                return second.strategy_variant
            # No challenger yet — create a v2 label
            base = best.strategy_variant.rsplit('_v', 1)[0]
            return f"{base}_v2"
    except Exception:
        pass

    # Default: map LD type to baseline variant
    mode_for_ld = {
        'adhd': 'focus',
        'anxiety': 'calm',
    }.get(ld_type, 'auto')
    return MODE_VARIANT_MAP.get(mode_for_ld, 'auto_v1')


# ── Internal helpers ──────────────────────────────────────────────

def _variant_to_ld_type(variant: str) -> str:
    """Infer a primary LD type from a variant name."""
    if variant.startswith('focus'):
        return 'adhd'
    if variant.startswith('calm'):
        return 'anxiety'
    if variant.startswith('speed'):
        return 'advanced'
    return 'general'


def _ld_set_to_primary(ld_set: set) -> str:
    """Return the most specific LD type from a set."""
    priority = ['adhd', 'anxiety', 'dyslexia', 'executive_function']
    for ld in priority:
        if ld in ld_set:
            return ld
    return 'general'
